import * as C from '@remnawave/backend-contract';
import { contractTool as t, type ContractCommand, type Tool } from './contract.js';
import { compactNodes, without } from './compact.js';

/**
 * Tool name → contract command. Everything else (route, method, arguments,
 * default description) is read from the command.
 *
 * `kind` is given only where the HTTP method is misleading: a POST that just
 * reads, or a POST that deletes data / touches every user or node.
 *
 * test/coverage.test.mjs fails when the contract gains a command that is
 * neither listed here nor in EXCLUDED_COMMANDS — so a contract bump is reviewed,
 * not silently ignored.
 */

const READ = { kind: 'read' } as const;
const DESTRUCTIVE = { kind: 'destructive' } as const;

const JOB = (resultTool: string) => `Starts a job on the node(s) and returns a jobId — fetch the outcome with ${resultTool}.`;

export const TOOLSETS: Record<string, Tool[]> = {
    users: [
        t('users_list', C.GetUsersCommand, {
            description:
                'List users with offset pagination and optional TanStack-style filters. To find users by telegramId, email, tag, ' +
                'status etc. pass filters, e.g. [{"id":"telegramId","value":123456789}]. Users are identified by numeric id.',
        }),
        t('users_stream', C.GetUsersStreamCommand),
        t('users_get', C.GetUserByIdCommand),
        t('users_get_by_username', C.GetUserByUsernameCommand),
        t('users_get_by_short_uuid', C.GetUserByShortUuidCommand),
        t('users_resolve', C.ResolveUserCommand, { ...READ, description: 'Resolve a user by EXACTLY ONE of: id, shortUuid, username' }),
        t('users_tags_list', C.GetUsersTagsCommand),
        t('users_accessible_nodes', C.GetUserAccessibleNodesCommand, {
            description:
                'Which nodes a user can actually reach: per node — config profile, active squads and their inbounds. ' +
                'Handy for debugging squad/inbound routing.',
        }),
        t('users_subscription_request_history', C.GetUserSubscriptionRequestHistoryCommand),
        t('users_create', C.CreateUserCommand, {
            description:
                'Create a user. Credentials (vlessUuid/ssPassword/trojanPassword/shortUuid) are generated by the panel unless ' +
                'given — pass them explicitly for service users.',
        }),
        t('users_update', C.UpdateUserCommand, { description: 'Update a user. Identify by id OR username.' }),
        t('users_delete', C.DeleteUserCommand),
        t('users_enable', C.EnableUserCommand),
        t('users_disable', C.DisableUserCommand),
        t('users_revoke_subscription', C.RevokeUserSubscriptionCommand, {
            description: 'Revoke user subscription: rotates the subscription link (and credentials unless told otherwise)',
        }),
        t('users_reset_traffic', C.ResetUserTrafficCommand),
        t('users_extend_expiration', C.ExtendUserCommand),
        t('users_bulk_update', C.BulkUpdateUsersCommand),
        t('users_bulk_update_squads', C.BulkUpdateUsersSquadsCommand),
        t('users_bulk_extend_expiration', C.BulkExtendExpirationDateCommand),
        t('users_bulk_reset_traffic', C.BulkResetTrafficUsersCommand),
        t('users_bulk_revoke_subscription', C.BulkRevokeUsersSubscriptionCommand),
        t('users_bulk_delete', C.BulkDeleteUsersCommand, DESTRUCTIVE),
        t('users_bulk_delete_by_status', C.BulkDeleteUsersByStatusCommand, {
            ...DESTRUCTIVE,
            description: 'Delete ALL users that have the given status',
        }),
        t('users_bulk_all_update', C.BulkAllUpdateUsersCommand, { ...DESTRUCTIVE, description: 'Update EVERY user at once' }),
        t('users_bulk_all_reset_traffic', C.BulkAllResetTrafficUsersCommand, {
            ...DESTRUCTIVE,
            description: 'Reset used traffic for EVERY user',
        }),
        t('users_bulk_all_extend_expiration', C.BulkAllExtendExpirationDateCommand, {
            ...DESTRUCTIVE,
            description: 'Extend expiration date for EVERY user by days',
        }),
    ],

    nodes: [
        t('nodes_list', C.GetNodesCommand, {
            ...compactNodes,
            description:
                'List all nodes. Compact by default: inbounds as tags, provider as name, system info trimmed. ' +
                'Pass full=true for the raw panel response, or use nodes_get for one node.',
        }),
        t('nodes_get', C.GetNodeCommand),
        t('nodes_tags_list', C.GetNodesTagsCommand),
        t('nodes_create', C.CreateNodeCommand),
        t('nodes_update', C.UpdateNodeCommand),
        t('nodes_delete', C.DeleteNodeCommand),
        t('nodes_enable', C.EnableNodeCommand),
        t('nodes_disable', C.DisableNodeCommand),
        t('nodes_restart', C.RestartNodeCommand),
        t('nodes_restart_all', C.RestartAllNodesCommand, { ...DESTRUCTIVE, description: 'Restart EVERY node' }),
        t('nodes_reset_traffic', C.ResetNodeTrafficCommand),
        t('nodes_reorder', C.ReorderNodesCommand),
        t('nodes_bulk_actions', C.BulkNodesActionsCommand),
        t('nodes_bulk_update', C.BulkNodesUpdateCommand),
        t('nodes_bulk_profile_modification', C.BulkNodesProfileModificationCommand),
        t('keygen_get', C.GetNodeSecretKeyCommand),
        t('node_integrations_list', C.GetNodeIntegrationsCommand),
        t('node_integrations_get', C.GetNodeIntegrationCommand),
        t('node_integrations_create', C.CreateNodeIntegrationCommand),
        t('node_integrations_update', C.UpdateNodeIntegrationCommand),
        t('node_integrations_delete', C.DeleteNodeIntegrationCommand),
    ],

    hosts: [
        t('hosts_list', C.GetHostsCommand),
        t('hosts_get', C.GetHostCommand),
        t('hosts_tags_list', C.GetHostsTagsCommand),
        t('hosts_create', C.CreateHostCommand),
        t('hosts_update', C.UpdateHostCommand),
        t('hosts_clone', C.CloneHostCommand),
        t('hosts_delete', C.DeleteHostCommand),
        t('hosts_reorder', C.ReorderHostsCommand),
        t('hosts_bulk_enable', C.BulkEnableHostsCommand),
        t('hosts_bulk_disable', C.BulkDisableHostsCommand),
        t('hosts_bulk_update', C.UpdateManyHostsCommand, {
            description: 'Update many hosts at once: the given fields (same as hosts_update) are applied to every host in `uuids`',
        }),
        t('hosts_bulk_delete', C.BulkDeleteHostsCommand, DESTRUCTIVE),
    ],

    config_profiles: [
        t('config_profiles_list', C.GetConfigProfilesCommand, {
            ...without('config', 'rawInbound'),
            description:
                'List config profiles with their inbounds and nodes. The xray config itself is left out: ' +
                'use config_profiles_get for one profile, or full=true.',
        }),
        t('config_profiles_get', C.GetConfigProfileByUuidCommand),
        t('config_profiles_get_computed_config', C.GetComputedConfigProfileByUuidCommand),
        t('config_profiles_get_inbounds', C.GetInboundsByProfileUuidCommand),
        t('inbounds_list', C.GetAllInboundsCommand, {
            ...without('rawInbound'),
            description: 'List inbounds of all config profiles (tag, type, port, squads). full=true adds the raw xray inbound objects.',
        }),
        t('config_profiles_tags_list', C.GetConfigProfilesTagsCommand),
        t('config_profiles_create', C.CreateConfigProfileCommand),
        t('config_profiles_update', C.UpdateConfigProfileCommand, {
            description: 'Update a config profile: name and/or the full xray config. Nodes that use the profile restart xray to apply it.',
        }),
        t('config_profiles_set_tags', C.SetConfigProfileTagsCommand),
        t('config_profiles_reorder', C.ReorderConfigProfileCommand),
        t('config_profiles_delete', C.DeleteConfigProfileCommand),
        t('snippets_list', C.GetSnippetsCommand),
        t('snippets_create', C.CreateSnippetCommand),
        t('snippets_update', C.UpdateSnippetCommand),
        t('snippets_sync', C.SyncSnippetCommand),
        t('snippets_delete', C.DeleteSnippetCommand),
    ],

    squads: [
        t('squads_list', C.GetInternalSquadsCommand, {
            ...without('rawInbound'),
            description: 'List internal squads with their inbounds. full=true adds the raw xray inbound objects.',
        }),
        t('squads_get', C.GetInternalSquadCommand),
        t('squads_accessible_nodes', C.GetInternalSquadAccessibleNodesCommand),
        t('squads_tags_list', C.GetInternalSquadsTagsCommand),
        t('squads_create', C.CreateInternalSquadCommand),
        t('squads_update', C.UpdateInternalSquadCommand),
        t('squads_set_tags', C.SetInternalSquadTagsCommand),
        t('squads_reorder', C.ReorderInternalSquadCommand),
        t('squads_add_many_users', C.AddManyUsersToInternalSquadCommand),
        t('squads_remove_many_users', C.DeleteManyUsersFromInternalSquadCommand, { kind: 'write' }),
        t('squads_add_all_users', C.AddUsersToInternalSquadCommand, {
            ...DESTRUCTIVE,
            description: 'Add EVERY user to an internal squad. For selected users use squads_add_many_users.',
        }),
        t('squads_remove_all_users', C.DeleteUsersFromInternalSquadCommand, {
            description: 'Remove EVERY user from an internal squad. For selected users use squads_remove_many_users.',
        }),
        t('squads_delete', C.DeleteInternalSquadCommand),
        t('external_squads_list', C.GetExternalSquadsCommand),
        t('external_squads_get', C.GetExternalSquadByUuidCommand),
        t('external_squads_tags_list', C.GetExternalSquadsTagsCommand),
        t('external_squads_create', C.CreateExternalSquadCommand),
        t('external_squads_update', C.UpdateExternalSquadCommand),
        t('external_squads_set_tags', C.SetExternalSquadTagsCommand),
        t('external_squads_reorder', C.ReorderExternalSquadCommand),
        t('external_squads_add_all_users', C.AddUsersToExternalSquadCommand, {
            ...DESTRUCTIVE,
            description: 'Add EVERY user to an external squad',
        }),
        t('external_squads_remove_all_users', C.DeleteUsersFromExternalSquadCommand, {
            description: 'Remove EVERY user from an external squad',
        }),
        t('external_squads_delete', C.DeleteExternalSquadCommand),
    ],

    hwid: [
        t('hwid_devices_list', C.GetUserHwidDevicesCommand),
        t('hwid_devices_list_all', C.GetHwidDevicesCommand),
        t('hwid_stats', C.GetHwidDevicesStatsCommand),
        t('hwid_top_users', C.GetTopUsersByHwidDevicesCommand),
        t('hwid_device_create', C.CreateUserHwidDeviceCommand),
        t('hwid_device_delete', C.DeleteUserHwidDeviceCommand, DESTRUCTIVE),
        t('hwid_devices_delete_all', C.DeleteAllUserHwidDevicesCommand, DESTRUCTIVE),
    ],

    subscriptions: [
        t('subscriptions_list', C.GetSubscriptionsCommand),
        t('subscriptions_get_by_user_id', C.GetSubscriptionByIdCommand),
        t('subscriptions_get_by_username', C.GetSubscriptionByUsernameCommand),
        t('subscriptions_get_by_short_uuid', C.GetSubscriptionByShortUuidProtectedCommand),
        t('subscriptions_get_raw_by_short_uuid', C.GetRawSubscriptionByShortUuidCommand),
        t('subscriptions_get_connection_keys', C.GetConnectionKeysByUserIdCommand),
        t('subscription_info', C.GetSubscriptionInfoByShortUuidCommand),
        t('subscription_request_history_list', C.GetSubscriptionRequestHistoryCommand),
        t('subscription_request_history_stats', C.GetSubscriptionRequestHistoryStatsCommand),
        t('subscription_settings_get', C.GetSubscriptionSettingsCommand),
        t('subscription_settings_update', C.UpdateSubscriptionSettingsCommand),
        t('subscription_templates_list', C.GetSubscriptionTemplatesCommand),
        t('subscription_templates_get', C.GetSubscriptionTemplateCommand),
        t('subscription_templates_tags_list', C.GetSubscriptionTemplatesTagsCommand),
        t('subscription_templates_create', C.CreateSubscriptionTemplateCommand),
        t('subscription_templates_update', C.UpdateSubscriptionTemplateCommand),
        t('subscription_templates_set_tags', C.SetSubscriptionTemplateTagsCommand),
        t('subscription_templates_reorder', C.ReorderSubscriptionTemplateCommand),
        t('subscription_templates_delete', C.DeleteSubscriptionTemplateCommand),
        t('sub_page_configs_list', C.GetSubpageConfigsCommand),
        t('sub_page_configs_get', C.GetSubpageConfigCommand),
        t('sub_page_configs_tags_list', C.GetSubpageConfigsTagsCommand),
        t('sub_page_configs_create', C.CreateSubpageConfigCommand),
        t('sub_page_configs_update', C.UpdateSubpageConfigCommand),
        t('sub_page_configs_clone', C.CloneSubpageConfigCommand),
        t('sub_page_configs_set_tags', C.SetSubpageConfigTagsCommand),
        t('sub_page_configs_reorder', C.ReorderSubpageConfigsCommand),
        t('sub_page_configs_delete', C.DeleteSubpageConfigCommand),
    ],

    node_plugins: [
        t('node_plugins_list', C.GetNodePluginsCommand),
        t('node_plugins_get', C.GetNodePluginCommand),
        t('node_plugins_tags_list', C.GetNodePluginsTagsCommand),
        t('node_plugins_create', C.CreateNodePluginCommand),
        t('node_plugins_update', C.UpdateNodePluginCommand),
        t('node_plugins_clone', C.CloneNodePluginCommand),
        t('node_plugins_set_tags', C.SetNodePluginTagsCommand),
        t('node_plugins_reorder', C.ReorderNodePluginCommand),
        t('node_plugins_sync', C.SyncNodePluginCommand),
        t('node_plugins_execute', C.PluginExecutorCommand),
        t('node_plugins_delete', C.DeleteNodePluginCommand),
        t('node_plugins_torrent_reports', C.GetTorrentBlockerReportsCommand),
        t('node_plugins_torrent_stats', C.GetTorrentBlockerReportsStatsCommand),
        t('node_plugins_torrent_truncate', C.TruncateTorrentBlockerReportsCommand),
        t('shared_lists_list', C.GetSharedListsCommand),
        t('shared_lists_get', C.GetSharedListCommand),
        t('shared_lists_create', C.CreateSharedListCommand),
        t('shared_lists_update', C.UpdateSharedListCommand),
        t('shared_lists_sync', C.SyncSharedListCommand),
        t('shared_lists_delete', C.DeleteSharedListCommand),
    ],

    connections: [
        t('connections_by_user_request', C.ConnectionsByUserCommand, {
            ...READ,
            description: `Request the active connections (IPs) of a user. ${JOB('connections_by_user_result')}`,
        }),
        t('connections_by_user_result', C.ConnectionsByUserResultCommand),
        t('connections_by_node_request', C.ConnectionsByNodeCommand, {
            ...READ,
            description: `Request the active connections on a node. ${JOB('connections_by_node_result')}`,
        }),
        t('connections_by_node_result', C.ConnectionsByNodeResultCommand),
        t('connections_geocheck_request', C.GeocheckByNodeCommand, {
            ...READ,
            description: `Check how a node's exit IP is geolocated. ${JOB('connections_geocheck_result')}`,
        }),
        t('connections_geocheck_result', C.GeocheckByNodeResultCommand),
        t('connections_drop', C.DropConnectionsCommand, DESTRUCTIVE),
    ],

    stats: [
        t('system_stats', C.GetStatsCommand),
        t('system_stats_recap', C.GetRecapCommand),
        t('system_stats_digest', C.GetStatsDigestCommand),
        t('system_http_stats', C.GetHttpStatsCommand),
        t('system_bandwidth_stats', C.GetBandwidthStatsCommand),
        t('system_nodes_statistics', C.GetNodesStatisticsCommand),
        t('system_nodes_metrics', C.GetNodesMetricsCommand),
        t('bandwidth_nodes_usage', C.GetStatsNodesUsageCommand),
        t('bandwidth_node_users', C.GetStatsNodeUsersUsageCommand),
        t('bandwidth_nodes_users', C.GetStatsNodesUsersUsageCommand, READ),
        t('bandwidth_nodes_usage_threshold', C.GetNodeUsageCommand, READ),
        t('bandwidth_user_usage', C.GetStatsUserUsageCommand),
        t('bandwidth_squad_usage', C.GetInternalSquadUsageCommand),
        t('bandwidth_squad_user_usage', C.GetInternalSquadUserUsageCommand),
    ],

    system: [
        t('system_health', C.GetRemnawaveHealthCommand),
        t('system_metadata', C.GetMetadataCommand, { description: 'Get panel version and build information' }),
        t('system_configuration', C.GetConfigurationCommand),
        t('system_generate_x25519', C.GenerateX25519Command),
        t('system_srr_matcher', C.TestSrrMatcherCommand, {
            ...READ,
            description:
                'Validate a subscription response rules (SRR) config against the panel matcher. ' +
                'The body is the full responseRules config object, not an input string.',
        }),
        t('auth_status', C.GetStatusCommand),
        t('settings_get', C.GetRemnawaveSettingsCommand),
        t('settings_update', C.UpdateRemnawaveSettingsCommand),
        t('api_tokens_list', C.GetApiTokensCommand),
        t('api_tokens_scopes', C.GetApiTokenScopesCommand),
        t('api_tokens_create', C.CreateApiTokenCommand),
        t('api_tokens_delete', C.DeleteApiTokenCommand),
        t('metadata_node_get', C.GetNodeMetadataCommand),
        t('metadata_node_upsert', C.UpsertNodeMetadataCommand),
        t('metadata_user_get', C.GetUserMetadataCommand),
        t('metadata_user_upsert', C.UpsertUserMetadataCommand),
    ],

    billing: [
        t('billing_providers_list', C.GetInfraProvidersCommand),
        t('billing_provider_get', C.GetInfraProviderCommand),
        t('billing_provider_create', C.CreateInfraProviderCommand),
        t('billing_provider_update', C.UpdateInfraProviderCommand),
        t('billing_provider_delete', C.DeleteInfraProviderCommand),
        t('billing_nodes_list', C.GetInfraBillingNodesCommand),
        t('billing_node_create', C.CreateInfraBillingNodeCommand),
        t('billing_node_update', C.UpdateInfraBillingNodeCommand),
        t('billing_node_delete', C.DeleteInfraBillingNodeCommand),
        t('billing_history_list', C.GetInfraBillingRecordsCommand),
        t('billing_history_create', C.CreateInfraBillingRecordCommand),
        t('billing_history_delete', C.DeleteInfraBillingRecordCommand),
    ],
};

/** Contract commands that deliberately have no tool. */
export const EXCLUDED_COMMANDS: { command: ContractCommand; why: string }[] = [
    // Interactive panel sign-in: an API token never needs these.
    { command: C.LoginCommand, why: 'interactive sign-in' },
    { command: C.RegisterCommand, why: 'interactive sign-in' },
    { command: C.OAuth2AuthorizeCommand, why: 'interactive sign-in' },
    { command: C.OAuth2CallbackCommand, why: 'interactive sign-in' },
    { command: C.GetPasskeyAuthenticationOptionsCommand, why: 'interactive sign-in' },
    { command: C.VerifyPasskeyAuthenticationCommand, why: 'interactive sign-in' },
    { command: C.GetPasskeysCommand, why: 'passkey management in the browser' },
    { command: C.UpdatePasskeyCommand, why: 'passkey management in the browser' },
    { command: C.DeletePasskeyCommand, why: 'passkey management in the browser' },
    { command: C.GetPasskeyRegistrationOptionsCommand, why: 'passkey management in the browser' },
    { command: C.VerifyPasskeyRegistrationCommand, why: 'passkey management in the browser' },
    { command: C.GetOttCommand, why: 'one-time token for browser tools (Swagger, Bull Board)' },
    { command: C.CreateSshTicketCommand, why: 'interactive SSH terminal' },
    { command: C.EvaluateVaultCommand, why: 'interactive SSH terminal' },
    { command: C.GetSubpageConfigByShortUuidCommand, why: 'GET with a request body, used by the subscription page itself' },
];
